name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.7.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.11.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t sussap/account-service:${{ github.sha }} -f app/Dockerfile .
          docker push sussap/account-service:${{ github.sha }}
